---
- name: Ensure PostgreSQL data directory exists.
  ansible.builtin.file:
    path: "{{ postgresql_data_dir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: Ensure PostgreSQL conf directory exists.
  ansible.builtin.file:
    path: "{{ postgresql_confs_dir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: Ensure PostgreSQL bin directory exists
  ansible.builtin.file:
    path: "{{ postgresql_bin_dir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: Set listen_addresses to
  community.postgresql.postgresql_set:
    name: listen_addresses
    value: "{{ postgresql_connection_ip }}"
  become: true
  become_user: "{{ postgresql_user }}"
  notify: Restart PostgreSQL

- name: "Ensure PostgreSQL is running"
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes