---
- name: Ensure PostgreSQL data directory exists.
  ansible.builtin.file:
    path: "{{ postgresql_data_dir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: Ensure PostgreSQL conf directory exists.
  ansible.builtin.file:
    path: "{{ postgresql_conf_files }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: Ensure PostgreSQL bin directory exists
  ansible.builtin.file:
    path: "{{ postgresql_bin_dir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: "Init postgresql database cluster"
  ansible.builtin.command:
    cmd: "{{ postgresql_bin_dir }}/initdb -D {{ postgresql_data_dir }}"
  become: yes
  become_user: "{{ postgresql_user }}"
  register: postgresql_cluster

- name: "Copy postgresql.conf"
  ansible.builtin.template:
    src: "postgresql.conf.j2"
    dest: "{{ postgresql_conf_files }}/postgresql.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
  notify: "Restart PostgreSQL"

- name: "Copy pg_hba.conf"
  ansible.builtin.template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_conf_files }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
  notify: "Restart PostgreSQL"

- name: "Ensure PostgreSQL is running"
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes