---
- name: "Copy postgresql.conf"
  ansible.builtin.template:
    src: "postgresql.conf.j2"
    dest: "{{ conf_files_location }}/postgresql.conf"
    owner: postgres
    group: postgres
  notify: "Restart PostgreSQL"

- name: "Copy pg_hba.conf"
  ansible.builtin.template:
    src: "pg_hba.conf.j2"
    dest: "{{ conf_files_location }}/pg_hba.conf"
    owner: postgres
    group: postgres
  notify: "Restart PostgreSQL"

- name: "Ensure PostgreSQL is running"
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes