---
- name: Include vars
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- name: Add apt repository
  ansible.builtin.deb822_repository:
    name: postgresql
    types: deb
    uris: "{{ postgresql_apt_url }}"
    suites: "{{ ansible_distribution_release }}-pgdg"
    components: "{{ postgresql_version_type }}"
    signed_by: "{{ postgresql_gpgkey }}"

- name: Update cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install PostgreSQL packages
  ansible.builtin.apt:
    name: " {{ postgresql_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600