---
- name: Include vars
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- name: Update cache
  ansible.builtin.apt:
    update_cache: true

- name: Install python packages
  ansible.builtin.apt:
    name: "{{ pg_python_packages }}"
    state: present

- name: Add apt repository
  ansible.builtin.deb822_repository:
    name: postgresql
    types: deb
    uris: "{{ pg_apt_url }}"
    suites: "{{ ansible_distribution_release }}-pgdg"
    components: "{{ pg_version_type }}"
    signed_by: "{{ pg_gpgkey }}"

- name: Update cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install PostgreSQL packages
  ansible.builtin.apt:
    name: "{{ pg_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600