---
- name: Include vars
  ansible.builtin.include_vars: "{{ ansible_distribution }}"

- name: Add yum repository
  ansible.builtin.yum_repository:
    name: postgresql
    state: present
    description: postgresql yum repo
    baseurl: "{{ postgresql_yum_repository_url }}"
    gpgkey: "{{ postgresql_yum_repository_gpgkey }}"
    enabled: yes

- name: Install PostgreSQL
  ansible.builtin.yum:
    name:
      - "postgresql{{ postgresql_version }}-server"
      - "postgresql{{ postgresql_version }}"
      - "postgresql{{ postgresql_version }}-contrib"
    state: present
    update_cache: yes

