---
- name: Include vars
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- name: Add yum repository
  ansible.builtin.yum_repository:
    name: postgresql
    state: present
    description: postgresql yum repo
    baseurl: "{{ postgresql_yum_repository_url }}"
    gpgkey: "{{ postgresql_yum_repository_gpgkey }}"
    enabled: yes

- name: Update cache
  ansible.builtin.yum:
    update_cache: yes

- name: Install PostgreSQL packages
  ansible.builtin.yum:
    name: "{{ postgresql_packages }}"
    state: present
    update_cache: yes

