---
- ansible.builtin.include_tasks: install_debian.yml
  when: ansible_distribution == 'Debian'

- ansible.builtin.include_tasks: install_alma.yml
  when: ansible_distribution == 'AlmaLinux'

- ansible.builtin.include_tasks: initialize.yml

- ansible.builtin.include_tasks: user_acces.yml