---
- name: Install PostgreSQL on Debian
  ansible.builtin.include_tasks: install_debian.yml
  when: ansible_os_family == 'Debian'

- name: Install PostgreSQL on RHEL
  ansible.builtin.include_tasks: install_rhel.yml
  when: ansible_os_family == 'RedHat'

- name: Initialize PostgreSQL
  ansible.builtin.include_tasks: initialize.yml

- name: Grant access to user
  ansible.builtin.include_tasks: user_access.yml
