---
- name: Install PostgreSQL on Debian
  ansible.builtin.include_tasks: install_debian.yml
  when: ansible_distribution == 'Debian'

- name: Install PostgreSQL on AlmaLinux
  ansible.builtin.include_tasks: install_alma.yml
  when: ansible_distribution == 'AlmaLinux'

- name: Initialize PostgreSQL
  ansible.builtin.include_tasks: initialize.yml

- name: Grant access to user
  ansible.builtin.include_tasks: user_access.yml
