---
- name: Create PostgreSQL user
  community.postgresql.postgresql_user:
    login_user: "{{ pg_user }}"
    name: "{{ pg_db_user }}"
    password: "{{ pg_db_user_password }}"
    role_attr_flags: LOGIN
    state: present
  become: true
  become_user: postgres

- name: Grant user access to some db
  community.postgresql.postgresql_pg_hba:
    dest: "{{ pg_confs_dir }}/pg_hba.conf"
    contype: host
    users: "{{ pg_db_user }}"
    databases: "{{ pg_database }}"
    method: md5
    source: "{{ pg_source_addr }}"
    create: true
    state: present
  become: true
  become_user: "{{ pg_user }}"
  notify: Reload postgresql conf
