---
- name: Restart PostgreSQL
  ansible.builtin.service:
    name: "{{ pg_service }}"
    state: restarted

- name: Reload PostgreSQL
  ansible.builtin.service:
    name: "{{ pg_service }}"
    state: reloaded

- name: Reload postgresql conf
  community.postgresql.postgresql_query:
    db: postgres
    query: SELECT pg_reload_conf()
  become: true
  become_user: "{{ pg_user }}"