---
- name: Converge
  hosts: all
  become: true
  vars:
    pg_db_user: "test_user"
    pg_db_user_password: "test_password"
    pg_source_addr: "172.17.0.0/16"
    pg_database: "test_db"
    pg_version: 17

  roles:
    - role: ansible-role-postgresql

  tasks:
    - name: Verify PostgreSQL is running
      ansible.builtin.service:
        name: "{{ pg_service }}"
        state: started
      register: pg_status

    - name: Check PostgreSQL connection
      community.postgresql.postgresql_ping:
        login_user: "{{ pg_db_user }}"
        login_password: "{{ pg_db_user_password }}"
        login_host: localhost
        db: "{{ pg_database }}"
      register: pg_ping
